### ISSUE TITLE
Engelse versie

### ISSUE THREAD

**Issue by woutervriel** [Logius-standaarden/BOMOS-Fundament#10]
### Soort

- [ ] Tekstuele fout
- [X] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

Wordt BOMOS ook in de Engels gepubliceerd? De informatie in het document is dermate nuttig dat we dat niet enkel voor de NL gebruiker hoeven te limiteren. Ik werk zelf aan modelontwikkeling bij TenneT en binnen die internationaal georiënteerde organisatie zou dat erg waardevol zijn.

### Naam

Wouter van Riel

### Email

wouter.van.riel@infralytics.org

### Organisatie

infralytics

**Comment by edwinwisse** [comment]
Dank voor je suggestie. Mooi om te horen dat je BOMOS waardevol vindt. Er is op dit moment geen plan om de huidige BOMOS versie naar engels te vertalen. De 3.0 versie is onlangs opgeleverd en in onze  gebruikersgroep zitten nu alleen nederlandse organisaties. We vinden je verbetervoorstel om internationaal te gaan heel goed en we zijn het met je eens. 

De vorige versie van BOMOS is destijds wel naar engels vertaald (zie [Guidelines for community management for standards – BOMOS2i | Joinup (europa.eu)](https://joinup.ec.europa.eu/collection/open-source-observatory-osor/event/guidelines-community-management-standards-bomos2i) Het heeft niet tot een blijvende internationale gebruikersgemeenschap geleid. Vertalen is immers niet genoeg. We zouden er echt capaciteit in moeten steken om een internationale gebruikersgroep te ondersteunen en die ruimte hebben we op dit moment niet.

**Comment by edwinwisse** [comment]
We sluiten deze vraag met bovenstaande verwijzing naar de engelse versie 2. Ook is er een kennismaking en bespreking geweest met de vraagsteller.
