### ISSUE TITLE
RFC ...

### ISSUE THREAD

**Issue by MVS11** [Logius-standaarden/BOMOS-Fundament#12]
### Soort

- [X] Tekstuele fout
- [ ] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

Paragraaf 4.3 toelichting activiteiten en rollen
tabel: term houder wijzigen in term eigenaar conform de ervoor benoemd rol. 

### Naam

Monique van Scherpenzeel

### Email

anononiem

### Organisatie

Geonovum

**Comment by isik001** [comment]
aangepast in respository

**Comment by edwinwisse** [comment]
Dank voor de correctie.
