### ISSUE TITLE
Onjuiste links

### ISSUE THREAD

**Issue by StephanyDeMaaijer** [Logius-standaarden/BOMOS-Fundament#13]
### Soort

- [X] Tekstuele fout
- [ ] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

Context. Helemaal onderaan bij de links werkt de link naar forum standaardisatie niet. Deze:
Open Standaard:  
[https://www.forumstandaardisatie.nl/thema/open-standaarden](https://www.forumstandaardisatie.nl/thema/open-standaarden)

deze link staat er 2x in:
Standardisation Handbook:
https://en.wikipedia.org/wiki/Open_standard (h staat ook als 2e link onder Open Standaard:

### Organisatie

Informatiehuis Water

**Comment by isik001** [comment]
review commentaar Stephanie verwerkt: werkende link toegevoegd: https://forumstandaardisatie.nl/open-standaarden en dubbele link  https://en.wikipedia.org/wiki/Open_standard verwijderd
